### ISSUE TITLE
typo in fuse-ios and fuse-android "about" descriptions

### ISSUE THREAD

**Issue by jcesarmobile** [btfuse/fuse-docs#1]
Since those repositories don't have issues enabled and the "about" section can't be changed from a pull request I'm reporting it here.

They both say `hybdrid natrive-web`, I think it should be `hybrid native-web`.

Also in fuse repository "about" section it says `hybdrid web-native`, I think it should be `hybrid web-native`.

But also for consistency, I think all the repositories should use the same term, web-native or native-web, but the same in all of them.

**Comment by breautek** [comment]
Thanks for pointing that out, I've corrected them.
